### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by missesmr**

### CODE REVIEW

**Comment by Kra1o5** [comment]
Really?

**Comment by missesmr** [comment]
yes it really boots , proof u want ?

**Comment by missesmr** [comment]
here's the proof

**Comment by Kra1o5** [comment]
We have it booting long time ago but not ril.

**Comment by missesmr** [comment]
no bro , ur thing boots then gets back to recovery
thats the thing

**Comment by missesmr** [comment]
the first build was with your tree , second build with my tree
and second one everything worked except ril
and i got a fix for ril too

**Comment by coolharsh91** [comment]
If u have a solution for ril, try and see of it works!

**Comment by coolharsh91** [comment]
*if

**Comment by missesmr** [comment]
yeah ofcourse and they will be no more pull requests too :D

**Comment by fefifofum** [comment]
Sure, and when you fix it we will use your fix, same as you use our repos.

**Comment by missesmr** [comment]
lol never , the time u take it from me i would have posted the rom in xda

**Comment by fefifofum** [comment]
Dont worry, it's not a race, even if you publish first we will publish it anyway. After all, you are using our work and fixing just one thing! Go for it!

**Comment by missesmr** [comment]
k -_-

**Comment by missesmr** [comment]
wifi doesnt work in cm12 guys
what to do ?

**Comment by TheStrix** [comment]
@fefifofum, wanna talk to u.. Can you meet on irc? Cz I dont see you online there too :/

**Comment by missesmr** [comment]
parth bhatia :3
you are back ?
we fixed ril and will provide rom soon

**Comment by TheStrix** [comment]
We? You fixed it?

**Comment by missesmr** [comment]
yes

**Comment by missesmr** [comment]
Parth Bhatia anyway to chat with you ?

**Comment by missesmr** [comment]
want to know how syhost fixed ril ???

**Comment by Kra1o5** [comment]
We dont need it.

& PLEASE stop posting here,

**Pull request closed without merging**
