### PR TITLE
armani: Specify supported radio capacities

### PR DESCRIPTION
**Pull request by TheStrix**
Now you can switch between 2G & 3G modes in SIM Preferred Network Type :)

### CODE REVIEW

**Comment by fefifofum** [comment]
I tested this some time ago, and it didn't seem to make a difference. Have you recently tested it? Or just cherry-picked from here? https://github.com/CyanogenMod/android_device_motorola_titan/commit/4f828a4d3664951f0246e84bea027467c4d1e71a

Are you sure our device doesn't support RIL_REQUEST_GET_RADIO_CAPABILITY? We can select non "GSM only" mode. Also, you forgot one variant (there are two variants for this device, see the init file). I will look into it when I have some time.

**Comment by TheStrix** [comment]
Yep, recently made a build with it and it works.
http://i.imgur.com/IK8XejZ.png & http://i.imgur.com/o2sa7UZ.png

**Comment by TheStrix** [comment]
Yep, take have to look into that other device.

**Comment by onano** [comment]
@fefifofum Seems like RIL_REQUEST_GET_RADIO_CAPABILITY macro is broken in generic msim implementation in ril hence this is needed. it needs more look at it.

**Comment by fefifofum** [comment]
Added!

**Pull request closed without merging**
