### PR TITLE
init: update build fingerprint from latest offcial release v7.1.1.0

### PR DESCRIPTION
**Pull request by onano**
update fingerprint to v7.1.1.0

### CODE REVIEW

**Comment by fefifofum** [comment]
Is this an official stable release, or a test build? I don't see it in the downloads section. Anyway, I'm more interested in the blobs than in the fingerprint, after all it's still a kitkat release.

**Comment by onano** [comment]
yep it's official global release, me too sorting changes in blobs out here too, here is link if you want : http://bigota.d.miui.com/V7.1.1.0.KHCMICK/miui_HM1SWCGlobal_V7.1.1.0.KHCMICK_c8e8009ea0_4.4.zip

**Comment by sufixescu** [comment]
Looking at the differential OTA patch http://obigota.d.miui.com/V7.1.1.0.KHCMICK/miui-ota-armani_global-V7.0.5.0.KHCMICI-V7.1.1.0.KHCMICK-6f558f1599-4.4.zip no major blob changed

**Comment by fefifofum** [comment]
Thanks, I'll check it out. @onano, I cherry-picked your fingerprint commit. I guess we can close this now.

**Pull request closed without merging**
