### PR TITLE
armani: enable multi-stream zram suppport

### PR DESCRIPTION
**Pull request by onano**
Performance Improvment in zram and improvement in power usage

Check Kernel pull : https://github.com/armani-dev/kernel_test/pull/8
support for this already merged in system_core : review.cyanogenmod.org/#/c/113323/1/

Change-Id: I0c150c29494f6b4a0831edee6af8aa19f893ae29
Signed-off-by: onano <mohit.srivastava@openmailbox.org>

### CODE REVIEW

**Comment by fefifofum** [comment]
Done!

**Comment by TechExhibeo** [comment]
@fefifofum and what about pull request in kernel?
https://github.com/armani-dev/kernel_test/pull/8
 we dont need them ?

**Comment by onano** [comment]
it is needed since those commits enable this feature, once rebase is done in kernel i'm sure he will merge it

**Comment by TechExhibeo** [comment]
Perfect :D
i thought he missed
so thought of reminding him :)
Thanks @onano for the info :)

**Pull request closed without merging**
