### PR TITLE
Remove media.stagefright properties

### PR DESCRIPTION
**Pull request by hemantbeast**
- Camera not working with the above commit's so remove them

### CODE REVIEW

**Comment by hemantbeast** [comment]
@fefifofum you also need to see this.
https://github.com/hemantbeast/xiaomi_armani_kernel/commits/cm-14.0

There are many commit's related to camera drivers, the camera working fine with the AICP 12, only problem is with video recording.

**Comment by fefifofum** [comment]
Video recording works with those media.stagefright properties and not without them. Anyway, video recording is still work in progress (in cm-14.0), so we have to be patient. I have no idea about AICP.
About camera drivers, keep in mind that we have kitkat camera blobs, so we have to be careful when updating camera in the kernel. I will take a look at those commits. Thanks!

**Comment by fefifofum** [comment]
I cherry-picked 3 commits that may help, but I guess I'm using a different source.

**Comment by hemantbeast** [comment]
Yeah I have seen it, and the patches in kernel needs to work camera. 

May be you should also look at this http://forum.xda-developers.com/showpost.php?p=69350297&postcount=42

**Pull request closed without merging**
