### PR TITLE
Cm 13.0 next

### PR DESCRIPTION
**Pull request by onano**
Introduce a ril class to handle Radio Capability , needed also for further extensions(?)

### CODE REVIEW

**Comment by TheStrix** [comment]
Umm, we already defined radio capabilities with this overlay and works fine :/
https://github.com/armani-dev/android_device_xiaomi_armani/blob/cm-13.0/overlay/frameworks/base/core/res/res/values/config.xml#L290

**Comment by onano** [comment]
Radio Capability in android is determined  First via RIL class if it doesn't find RIL capability there it checks into overlay as a fallback protection , if it is not available in overlay it breaks the process , hence leading to error , so, a method call is needed to fullfill proper conditions by OS.

**Comment by fefifofum** [comment]
I would try to avoid this, maybe we just need marshmallow ril blobs. I have to try the ones for cancro.

**Comment by onano** [comment]
sure, this commit is here if you need it :)

**Comment by onano** [comment]
https://github.com/android/platform_frameworks_base/commit/8c621ef54630e411d50e9ba1d8d8ed19ef93f9e1

more info for this patch :)

**Comment by TheStrix** [comment]
Yeah, I think overlay is okay. Even shamu uses same method for specifying it. 
https://android.googlesource.com/device/moto/shamu/+/android-6.0.1_r5/overlay/frameworks/base/core/res/res/values/config.xml#337

**Comment by onano** [comment]
Guess we don't need it now? closing pull

**Pull request closed without merging**
