### PR TITLE
CM 12.0 booting

### PR DESCRIPTION
**Pull request by zephyr2k**
The last commit allows CM-12.0 to boot without any hiccups. It's just a dirty hack to prevent qmuxed service from starting.
You can check for yourself. 
Getting wifi to work is a problem. There's a workaround, but it involves a lot of labour. 
I have successfully duplicated the conditions to get wifi working . 
If you are interested, I can provide it. Maybe we can work together to fix it.

Also kernel  used is https://github.com/zephyr2k/android_kernel_xiaomi_armani/tree/cm-12.0 . Hope it helps

### CODE REVIEW

**Comment by fefifofum** [comment]
Last time I built cm12 it was booting fine, and wifi was working also (after wipes).

**Comment by zephyr2k** [comment]
Could you point out the source, along with branch ? Are these correct ?
Device tree: https://github.com/armani-dev/android_device_xiaomi_armani/tree/cm-12.0 
Kernel : https://github.com/armani-dev/android_kernel_xiaomi_armani/commits/cm-11.0
Vendor : https://github.com/armani-dev/proprietary_vendor_xiaomi/tree/cm-12.0 .
Any other repo that need's  downloading ? like device_qcom_common ? or caf ?

**Comment by zephyr2k** [comment]
I compiled cm12 with the above provided links to double-check. Sure enough it compiled successfully.
I did a normal flash ( wiped everything ).  I had earlier flashed MIUI50 (clean) to make sure it had firmware updated.  It booted . On the wifi screen , it rebooted. 
Have a look a this log:
http://pastebin.com/ZHRRdLVA

**Comment by TheStrix** [comment]
@zephyr2k, the newer kk caf kernel boot loops on CM12 but you can try the old one(Xiaomi release). It boots... And talking about WiFi. It works.

Umm, @fefifofum, CM11 is quite stable now.. We should concentrate on CM12 :/

**Comment by zephyr2k** [comment]
I should have been specific about Wifi.
It so happens that disabling qmuxd, prevents wifi from getting initialized at boot, also prevents the bootloop. Also for the first 10-15 minutes of booting you cannot start wifi. Logcat shows -- Failed to Load Driver.  However after some time it loads. 

I have been investigating this issue which led me to :
https://groups.google.com/forum/#!topic/rowboat/9FhdYn-0mzw ,maybe 
The reason was that while bootlooping, if I could flash boot.img (same that compiled from build) over it. It would boot !!!
I experimented further by unpacking luffyXDA's kernel and packing with my ramdisk, it worked.

This brings me to my question , do device_perms.h files perform work for that purpose. Like assigning temporary permission at certain stage of booting, and reverting later on ?

**Comment by fefifofum** [comment]
I'm not going to look too much into cm12 until we have working ril blobs. This is my main phone and I need working ril to have cm12 installed.

**Pull request closed without merging**
