### PR TITLE
init.armani.power.rc

### PR DESCRIPTION
**Pull request by tarunkapadia93**
keep power profiles separate will keep the init.armani.rc much cleaner

### CODE REVIEW

**Comment by tarunkapadia93** [comment]
oops forgot device.mk entry for init.armani.power.rc pls do add it mate guess m too sleepy

**Comment by rebelos** [comment]
One question why all this?

**Comment by Devesh-Singh** [comment]
screenshot_2015-09-27-21-28-55 1
screenshot_2015-09-27-21-28-59 1
screenshot_2015-09-27-21-30-35 1



screenshot_2015-09-27-21-28-40 1
Hi All,
There are some real power consumption issue with the build. I am using this build on HM1s and even on flight mode with just wifi on, it doesn't even lasts a day.
Can we discuss this somewhere else. I really want to optimize the power consumption of this build.
On armani 11, it used to last approx 30hrs with wifi and on armani12.1 it only lasts 16 hrs on wifi. That too with all non-essential apps greenified.

I know this is not the right place, please send me a link to forum/group where we can discuss and improve upon.
screenshot_2015-09-27-21-25-50 1

**Comment by tarunkapadia93** [comment]
@rebelos  one thing its better to keep the init.armani.rc clean n secondly its easier for the kernel devs to mod power profile entries n things ;)

**Pull request closed without merging**
